[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e3c72"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
